version: "3"

networks:
  loki:

services:
  loki:
    restart: always
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    restart: always
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /opt/appmesh/:/opt/appmesh/
      - ./promtail.yml:/etc/promtail/config.yml
    # override default container config: /etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    depends_on:
      - loki

  grafana:
    restart: always
    image: grafana/grafana:latest
    #ports:
    #  - "3000:3000"
    network_mode: host

  # Prometheus, use host mode to scrap from other nodes
  prometheus:
    restart: always
    image: prom/prometheus:latest
    privileged: true
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    #ports:
    #  - "9090:9090"
    network_mode: host

  # https://www.cnblogs.com/weifeng1463/p/12828961.html
  node_exporter:
    restart: always
    image: prom/node-exporter:latest
    command: --path.procfs=/host/proc --path.rootfs=/rootfs --path.sysfs=/host/sys --collector.filesystem.ignored-mount-points='^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    #ports:
    #  - "9100:9100"
